export {
  db,
  BeanCounterDB,
  SETTINGS_SINGLETON_ID,
  type SettingsRecord,
} from './dexie'

export {
  useActiveLitters,
  useArchivedLitters,
  useAllLitters,
  useLitter,
  useActiveKittens,
  useArchivedKittens,
  useAllKittens,
  useSettings,
  useOpenSessionForLitter,
  useSession,
  useWeightEntriesForSession,
  useWeightForKittenInSession,
  useAllSessions,
  useAllWeightEntries,
} from './queries'

export {
  persistNewLitter,
  archiveLitterById,
  activateLitterById,
  renameLitterById,
  persistNewKitten,
  archiveKittenById,
  activateKittenById,
  renameKittenById,
  setStickyLitterById,
  clearStickyLitterById,
  persistKittenOrder,
  ensureOpenSessionForLitter,
  ensureOpenSessionWithRecordedAt,
  touchSessionById,
  completeSessionById,
  setSessionRecordedAtById,
  clearSessionRecordedAtById,
  persistWeightEntry,
  wipeAllData,
  type NewLitterInput,
  type NewLitterResult,
} from './mutations'
